Repository ComputerSocietyUNB/ProjetoChatbot, pull requests merged in 2018-09, with the labels that each got.

#37 Helpme
  bot/application.py
  bot/dialogs/contacts.md
  bot/dialogs/help.md
Labels: enhancement

#54 Desenvolve linter de yaml
  .codeclimate.yml
  .coveragerc
  .yamllint
  bot/application.py
  bot/communication.py
  bot/dialogs/greetings/greetings.yml
  bot/dialogs/jokes/jokes.yml
  bot/dialogs/linter.json
  bot/dialogs/removals/pronouns.json
  bot/dialogs/removals/punctuation.json
  bot/dialogs/switches/abbreviations.json
  bot/dialogs/triggers/triggers.yml
  linter/linter.py
  makefile
  requirements.txt
  tests/test_application.py
  tests/test_communication.py
  tests/test_dialogs.py
  tests/test_linter.py
Labels: devs, feature

#57 Invoke
  README.md
  bot/application.py
  bot/dialogs/feelings/feelings.yml
  requirements.txt
  tasks.py
  tests/test_application.py
  tests/test_communication.py
  tests/test_dialogs.py
Labels: chore, devs

#61 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore, devs

#63 Update tasks.py
  tasks.py
Labels: bugfix, devs

#65 Add documentation and invoke command for documentation
  bot/application.py
  bot/communication.py
  docs/Makefile
  docs/conf.py
  docs/faq.rst
  docs/index.rst
  docs/install.rst
  docs/license.rst
  docs/make.bat
  docs/overview.rst
  docs/tutorial.rst
  docs/warning.rst
  requirements.txt
  tasks.py
  tests/test_communication.py
Labels: chore, devs

#68 Add IBM Watson integration to bot flow
  .codeclimate.yml
  .gitignore
  .pyup.yml
  .travis.yml
  README.md
  bot/application.py
  bot/communication.py
  bot/config_reader.py
  bot/watson.py
  requirements.txt
  tasks.py
  tests/test_application.py
  tests/test_communication.py
  tests/test_config_reader.py
  tests/test_dialogs.py
  watson_tests/README.md
  watson_tests/categories.py
  watson_tests/entities.py
  watson_tests/mix.py
  watson_tests/setments.py
  watson_tests/simple_keywords.py
Labels: blocked, devs, feature
